FROM node:22-slim as build

WORKDIR /app

COPY tsconfig.json ./tsconfig.json
COPY package.json package-lock.json ./
COPY packages/web/package.json packages/web/package.json
COPY packages/backend/package.json packages/backend/tsconfig.json packages/backend/

RUN npm ci --legacy-peer-deps

COPY packages/web/ packages/web/
COPY packages/backend/src/ packages/backend/src/

RUN npm run build --workspace=@arete/web

FROM caddy:2.10.2-alpine

COPY --from=build /app/packages/web/dist /usr/share/caddy
COPY deploy/Caddyfile /etc/caddy/Caddyfile
