export const EMBED_FIELD_VALUE_LIMIT = 1024;
export const EMBED_FOOTER_TEXT_LIMIT = 2048;
export const EMBED_DESCRIPTION_LIMIT = 4096;
export const EMBED_TITLE_LIMIT = 256;
export const EMBED_MAX_FIELDS = 25;
export const EMBED_TOTAL_FIELD_CHAR_LIMIT = 6000;
export const PROMPT_DISPLAY_LIMIT = 512;
export const CLOUDINARY_CONTEXT_VALUE_LIMIT = 950;
export const PARTIAL_IMAGE_LIMIT = 3; // OpenAI's limit is 3
export const REFLECTION_TITLE_LIMIT = EMBED_TITLE_LIMIT;
export const REFLECTION_DESCRIPTION_LIMIT = EMBED_DESCRIPTION_LIMIT;
export const REFLECTION_MESSAGE_LIMIT = 2000; // Discord's max is 2000
export const DEFAULT_MODEL = 'gpt-4.1-mini';
export const IMAGE_VARIATION_CUSTOM_ID_PREFIX = 'image:variation:';
export const IMAGE_RETRY_CUSTOM_ID_PREFIX = 'image:retry:';
export const IMAGE_VARIATION_GENERATE_CUSTOM_ID_PREFIX = 'image:variation:generate:';
export const IMAGE_VARIATION_QUALITY_SELECT_PREFIX = 'image:variation:quality:';
export const IMAGE_VARIATION_BACKGROUND_SELECT_PREFIX = 'image:variation:background:';
export const IMAGE_VARIATION_PROMPT_ADJUST_SELECT_PREFIX = 'image:variation:prompt-adjust:';
export const IMAGE_VARIATION_ASPECT_SELECT_PREFIX = 'image:variation:aspect:';
export const IMAGE_VARIATION_PROMPT_MODAL_ID_PREFIX = 'image:variation:prompt:';
export const IMAGE_VARIATION_PROMPT_INPUT_ID = 'variationPrompt';
export const IMAGE_VARIATION_RESET_PROMPT_CUSTOM_ID_PREFIX = 'image:variation:reset-prompt:';
export const IMAGE_VARIATION_CANCEL_CUSTOM_ID_PREFIX = 'image:variation:cancel:';
